### ISSUE TITLE
PypiFacade: All CA root bundle installations failing is preventing pip configuration sandboxing

### ISSUE THREAD

**Issue by autumn-cpt** [devops-csmake/csmake-providers#18]
After installing pip 19.1.1 - pip isn't being automatically directed through the facade.  It's odd because installing pip 19 in an scl environment didn't seem to have the same problem.  It would also seem that the pip _vendor certs have moved.

**Comment by autumn-cpt** [comment]
This may not be a 19.1.1 issue.  The facade is having trouble putting the new .crt file into the ca-trust in the chroot.  This may be halting attempts to place the crt.

```
        &PypiFacade@(ChrootShell@build-wheel-files): EXCEPTION: Attempting to ensure configuration for '/home/autumn/CardinalPeak/nccc-docker/docker-wheels/target/builds/docker-wheels-image/etc/pki/ca-trust/source/anchors' failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/CsmakeProviders/CsmakeServiceProvider.py", line 853, in _ensureInstance
    entry.ensure()
  File "/usr/lib/python2.7/dist-packages/CsmakeProviders/PypiProvider.py", line 1709, in ensure
    False )
  File "/usr/lib/python2.7/dist-packages/CsmakeProviders/CsmakeServiceProvider.py", line 749, in shellout
    **keywords )
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['sudo', 'cp', '/tmp/tmplUS5w5/tempcerts/csmake-pypi-cert.crt', '/etc/pki/ca-trust/source/anchors/csmake-pypi-cert.crt']' returned non-zero exit status 1
        &PypiFacade@(ChrootShell@build-wheel-files): DEBUG    : Switching to notifier: /home/autumn/CardinalPeak/nccc-docker/docker-wheels/target/builds/docker-wheels-image/etc/pki/ca-trust/source/anchors

```

This is leading to empty pip.conf files as the content is subverted by the fact that there are "no CA bundles"

```
&PypiFacade@(ChrootShell@build-wheel-files): ^%^%^ DEV: shellout: <function check_output at 0x7f20bb07ab50>(['sudo', 'mv', './target/builds/docker-wheels-image/root/.pip/pip.conf', './target/builds/docker-wheels-image/root/.pip/pip.conf.csmake.bkup'], {'stderr': -2})
        &PypiFacade@(ChrootShell@build-wheel-files): ^%^%^ DEV: Attempting to move '/root/.pip/pip.conf' caused: Command '['sudo', 'mv', './target/builds/docker-wheels-image/root/.pip/pip.conf', './target/builds/docker-wheels-image/root/.pip/pip.conf.csmake.bkup']' returned non-zero exit status 1 (this is probably ok)
        &PypiFacade@(ChrootShell@build-wheel-files): ERROR    : There were no CA bundles to reference to install our temporary root CA
        &PypiFacade@(ChrootShell@build-wheel-files): ERROR    : There were no CA bundles to reference to install our temporary root CA
```

This seems to be the problem.  The question is why is the PypiFacade seemingly succeeding to install all of this with a different ChrootShell and taking over pip..... and removing that doesn't seem to fix the problem here...

**Comment by autumn-cpt** [comment]
how has `SSLCertificateDirectoryConfig` ever worked?  It doesn't reference the chroot path... this feels problematic

**Comment by autumn-cpt** [comment]
I added a fake path to the bundles and was able to get that to work, so on top of other weird problems, the single file path is simply not working properly `SSLCertificateDirectoryConfig` even with modifications to ensure the CA files actually get put in the right place.  It's still totally unable to function - but the fake bundle that is basically the same contents works just fine....gah

**Comment by autumn-cpt** [comment]
#20 is a huge issue contributing to this problem in the particular build I was working on.

**Comment by autumn-cpt** [comment]
In the "requests" vendor package, in pip 19.1.1, the pem file is moved....this is the root cause of the build failure.

**Comment by autumn-cpt** [comment]
certifi is now used by requests, new path is {PYTHONPATH}/pip/_vendor/certifi/cacert.pem
